version: "3.9"

services:
  rentxdb:
    container_name: rentx
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentxdb
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local

